/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { EntryDischarge, EntrySickLeave } from "./entryTypes.js";
import type { ColumnType } from "kysely";

export type EntryType = "HealthCheck" | "Hospital" | "OccupationalHealthcare";

export type Gender = "female" | "male" | "other";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type HealthCheckRating = "CriticalRisk" | "Healthy" | "HighRisk" | "LowRisk";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Diagnoses {
  code: string;
  latin: string | null;
  name: string;
}

export interface Entries {
  date: string;
  description: string;
  diagnosis_codes: string[] | null;
  discharge: EntryDischarge | null;
  employer_name: string | null;
  health_check_rating: HealthCheckRating | null;
  id: string;
  patient_id: string;
  row_id: Generated<number>;
  sick_leave: EntrySickLeave | null;
  specialist: string;
  type: EntryType;
}

export interface Patients {
  created_at: Generated<Timestamp>;
  date_of_birth: string;
  gender: Gender;
  id: string;
  name: string;
  occupation: string;
  ssn: string;
}

export interface DB {
  diagnoses: Diagnoses;
  entries: Entries;
  patients: Patients;
}
